Имя: NodeJS с Grunt

на:
  толкать:
    Ветви: [ "основной" ]
  pull_request:
    Ветви: [ "основной" ]

рабочие места:
  строить:
    ударять: Ubuntu-последний

    стратегия:
      матрица:
        версия узла: [14.Икс, 16.Икс, 18.Икс]

    шаги:
    - использует: действия/checkout@v3

    - Имя: Используйте Node.js ${{ матрица.node-версия }}
      использует: действия/setup-node@v3
      с:
        версия узла: ${{ матрица.node-версия }}

    - Имя: Строить
      бегать: |
        установка npm
        ворчать
